# Generated by Django 3.0.7 on 2020-06-24 02:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='images.jpg', upload_to='')),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('time_publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_update', models.DateTimeField(blank=True)),
                ('description', models.TextField(max_length=1000)),
                ('trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phone.Trademark')),
            ],
        ),
    ]
