# Generated by Django 3.0.7 on 2020-07-06 10:43

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='time_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
