# Generated by Django 3.0.7 on 2020-07-07 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0002_auto_20200706_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
